- name: Add an Apt signing key, will not download if present
  ansible.builtin.apt_key:
    id: D744D55EACDA69FF
    keyserver: keys.gnupg.net
    state: present

- name: Add FusionDirectory repostiory
  ansible.builtin.apt_repository:
    repo: deb http://repos.fusiondirectory.org/fusiondirectory-extra/debian-stretch stretch main
    state: present
