- name: Install fusiondirectory packages
  apt:
    name: 
      - fusiondirectory
      - fusiondirectory-schema
      - fusiondirectory-plugin-systems
      - fusiondirectory-plugin-mail
      - fusiondirectory-plugin-dovecot
      - fusiondirectory-plugin-ldapmanager
      - php-fpm
      - "{{ fusiondirectory_webserver }}"
    state: present
